# Generated by Django 3.0.5 on 2021-03-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='autor recenzji')),
                ('content', models.TextField(verbose_name='treść recenzji')),
                ('is_recommended', models.BooleanField(verbose_name='polecam innym')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='recenzja filmu')),
            ],
        ),
    ]
