# Generated by Django 3.0.5 on 2021-03-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'reżyser', 'verbose_name_plural': 'reżyserzy'},
        ),
    ]
